layout_spectrum: 0.7091423247475177
typography_spectrum: 0.008009646087884903
color:
  brandStrength: 0.3558779242448509
  lightness: 0.2567754609044641
  saturation: 0.7494009586516768
  rhythmicContrast: 0.5660005477257073
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
name: No Soup For You
navigation:
  - name: MUCHACHAS
    id: eb8343a6-26b1-46fb-84a7-b60d58e1d0bc
    type: content
